name: PR

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_DEV_DEBUG: 0
  RUST_BACKTRACE: 1

jobs:
  eslint-format:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f

      - name: Install mise
        uses: jdx/mise-action@v3
        with:
          install: true
          cache: true

      - name: Install dependencies
        run: mise run install

      - name: Perform linting
        run: mise run lint:front

  rust-format:
    name: rustfmt
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y \
              build-essential \
              curl \
              wget \
              file \
              libxdo-dev \
              libssl-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev \
              libwebkit2gtk-4.1-dev \
              patchelf \
              xdg-utils

      - name: Install mise
        uses: jdx/mise-action@v3
        with:
          install: true
          cache: true

      - name: Run rustfmt
        run: mise run format:back:check

  rust-lint:
    name: Clippy
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            os_name: linux
            rust_target: x86_64-unknown-linux-gnu
          - os: macos-latest
            os_name: macos
            rust_target: aarch64-apple-darwin
          - os: windows-latest
            os_name: windows
            rust_target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f

      - name: Install dependencies
        if: matrix.os_name == 'linux'
        run: |
          sudo apt-get update
          sudo apt install -y \
              build-essential \
              curl \
              wget \
              file \
              libxdo-dev \
              libssl-dev \
              libayatana-appindicator3-dev \
              librsvg2-dev \
              libwebkit2gtk-4.1-dev \
              patchelf \
              xdg-utils

      - name: Install mise
        uses: jdx/mise-action@v3
        with:
          install: true
          cache: true

      - name: Install OpenSSL on Windows
        if: matrix.os == 'windows-latest'
        run: choco install openssl

      - name: Set up Perl on Windows
        if: matrix.os == 'windows-latest'
        uses: shogo82148/actions-setup-perl@2fde72b7b7b24c986737ffc0eb0cbba8622c9d78
        with:
          perl-version: "5.32"
          distribution: "strawberry"

      - name: Set Perl environment variables
        if: matrix.os == 'windows-latest'
        run: |
          echo "PERL=$((where.exe perl)[0])" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          echo "OPENSSL_SRC_PERL=$((where.exe perl)[0])" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Configure Rust targets
        run: rustup target add ${{ matrix.rust_target }}
        shell: bash

      - name: Run Clippy
        run: mise run lint:back
